name: run unit tests
on: [push]

jobs:
  unit_test:
    name: Unit Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - uses: actions/checkout@v3

      - name: Run install yarn
        run: npm install -g yarn

      - name: Run install
        run: yarn install

      - name: Test the app
        run: yarn test:unit